apiVersion: apps/v1
kind: Deployment
metadata:
  name: campintontop-deployment
spec:
  selector:
    matchLabels:
      type: campingontop
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: campingontop
    spec:
      containers:
        - name: container
          image: tessssssssy/campingontop:5.VERSION
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 5